# Open API para los servicios del proyecto

openapi: 3.0.1
servers:
  - description: Index swagger
    #url local
    #-url: https://localhost:8080
    #url produccion
    url: https://api.samtel.co
info:
  description: Servicio de entidad Usuario.
  version: 0.0.1
  title: Usuarios
  contact:
    name: Samtel
    url: https://www.samtel.co/
    email: api@samtel.co
  license:
    name: GNU GPLv3
    url: ‘https://www.gnu.org/licenses/gpl-3.0.html’
tags:
  - name: Usuarios
    description: Gestion de usuarios
#----------------------------
#Endpoints de la Entidad
#----------------------------
paths:
# ------------------- Crear Usuario ---------------------
  /v1/es/crearUsuario: #La ruta de la api
    post:
      tags:
        - Crear usuario
      operationId: crearUsuario #metodo
      requestBody:
        description: Crear usuario
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsuarioTypeInput"
      responses:
        "200":
          description: Usuario creado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UsuarioTypeResponse"
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra la novedad."
# -------------------- Listar Usuario -------------------------
  /v1/es/buscarUsuarioId/{idtbl_user}:
    get:
      tags:
        - Buscar Usuario
      parameters:
        - in: path
          name: idtbl_user   # Note the name is the same as in the path
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      operationId: buscarUsuarioId
      responses:
        "200":
          description: Usuario encontrado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UsuarioTypeResponse"
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra la novedad."
#---------------- Eliminar Usuario ----------------
  /v1/es/eliminarUsuarioId/{idtbl_user}:
    delete:
      tags:
        - Eliminar Usuario
      parameters:
        - in: path
          name: idtbl_user   # Note the name is the same as in the path
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      operationId: eliminarUsuarioId
      responses:
        "200":
          description: Usuario eliminado.
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra la novedad."
#--------------- Listar Usuarios -----------------
  /v1/es/listadoUsuarios:
    get:
      tags:
        - Listar todos los usuario
      operationId: listarTodosLosUsuarios
      responses:
        "200":
          description: Lista de usuario.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UsuarioTypeResponse"
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra la novedad."
#------------- Actualizar Usuario ----------------
  /v1/es/editarUsuarioId/{idtbl_user}:
    put:
      tags:
        - Editar usuario
      parameters:
        - in: path
          name: idtbl_user   # Note the name is the same as in the path
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      operationId: editarUsuarioId
      requestBody:
        description: Editar usuario
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsuarioTypeInput"
      responses:
        "200":
          description: Usuario editado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UsuarioTypeResponse"
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra la novedad."
#---------------------------------------------
#Se declaran los Modelos/Schemas del servicio
#---------------------------------------------
components:
  schemas:
    UsuarioTypeResponse:
      type: object
      properties:
        name:
          type: string
        lastname:
          type: string
        createat:
          type: string
          format: date
    UsuarioTypeInput:
      type: object
      properties:
        name:
          type: string
        lastname:
          type: string
        createat:
          type: string
          format: date